
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjihzmwtdqnigkqbugrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqaWh6bXd0ZHFuaWdrcWJ1Z3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjc5MjQsImV4cCI6MjA2Njc0MzkyNH0.GLCHLkoLQtPmVSCeUEoH9ZGoYxOG6idNMcGd8IgiyqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
